import elevador

elevador = elevador.Elevador(total_andares=5, capacidade=5)

elevador.subir()
elevador.entrar()
elevador.entrar()
elevador.entrar()
elevador.entrar()
elevador.entrar()
elevador.entrar()
elevador.subir()
elevador.subir()
elevador.subir()
elevador.subir()
elevador.subir()
elevador.sair()
elevador.sair()
elevador.sair()
elevador.sair()
elevador.sair()
elevador.sair()
elevador.descer()
elevador.descer()
elevador.descer()
elevador.descer()
elevador.descer()
elevador.descer()
